// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbvy3_ijFjtdo-nfG7k-x5q3lMbQoStT0',
    appId: '1:308965646190:web:d864865158411bb4efeb7f',
    messagingSenderId: '308965646190',
    projectId: 'ecommerce-c606a',
    authDomain: 'ecommerce-c606a.firebaseapp.com',
    storageBucket: 'ecommerce-c606a.firebasestorage.app',
    measurementId: 'G-PY9JNF0P4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABgT8OuIbQP2NWUHYDZV8edezYHXv0mMs',
    appId: '1:308965646190:android:505919146296d462efeb7f',
    messagingSenderId: '308965646190',
    projectId: 'ecommerce-c606a',
    storageBucket: 'ecommerce-c606a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBawXWAoRdf0BFk5tVGlJ2c65xrsxWPp5w',
    appId: '1:308965646190:ios:8072e3e33b3bce73efeb7f',
    messagingSenderId: '308965646190',
    projectId: 'ecommerce-c606a',
    storageBucket: 'ecommerce-c606a.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBawXWAoRdf0BFk5tVGlJ2c65xrsxWPp5w',
    appId: '1:308965646190:ios:8072e3e33b3bce73efeb7f',
    messagingSenderId: '308965646190',
    projectId: 'ecommerce-c606a',
    storageBucket: 'ecommerce-c606a.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbvy3_ijFjtdo-nfG7k-x5q3lMbQoStT0',
    appId: '1:308965646190:web:9f73f4099dd9975cefeb7f',
    messagingSenderId: '308965646190',
    projectId: 'ecommerce-c606a',
    authDomain: 'ecommerce-c606a.firebaseapp.com',
    storageBucket: 'ecommerce-c606a.firebasestorage.app',
    measurementId: 'G-R4QDJF8GJJ',
  );
}
